/* ─── Shared services data ───
   Used by the Services page.
   When the backend is ready, replace this with API calls.
   ─────────────────────────────────────────────── */

/* ─── Service categories ─── */
export const serviceCategories = [
  { id: "all", label: "All services", icon: "🏠" },
  { id: "cleaning", label: "Cleaning", icon: "🧹" },
  { id: "photography", label: "Photography", icon: "📸" },
  { id: "chef", label: "Private chef", icon: "👨‍🍳" },
  { id: "transport", label: "Transport", icon: "🚗" },
  { id: "concierge", label: "Concierge", icon: "🛎️" },
  { id: "beauty", label: "Beauty & spa", icon: "💆" },
  { id: "fitness", label: "Fitness", icon: "💪" },
  { id: "childcare", label: "Childcare", icon: "👶" },
  { id: "pet", label: "Pet care", icon: "🐾" },
];

/* ─── Service listings ─── */
const services = [
  {
    id: "svc-1",
    title: "Professional Home Cleaning",
    category: "cleaning",
    image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=600&q=80",
    location: "Lahore, Pakistan",
    rating: 4.95,
    reviews: 238,
    price: 40,
    priceUnit: "per session",
    provider: {
      name: "CleanPro Lahore",
      image: "https://i.pravatar.cc/150?u=cleanpro",
      isVerified: true,
    },
    description: "Thorough cleaning by trained professionals. Includes dusting, mopping, bathroom and kitchen deep-clean. Eco-friendly products used.",
    duration: "3-4 hours",
    isPopular: true,
    highlights: ["Eco-friendly products", "Trained professionals", "Satisfaction guaranteed"],
  },
  {
    id: "svc-2",
    title: "Property Photography Package",
    category: "photography",
    image: "https://images.unsplash.com/photo-1554080353-a576cf803bda?w=600&q=80",
    location: "All cities",
    rating: 4.98,
    reviews: 412,
    price: 75,
    priceUnit: "per shoot",
    provider: {
      name: "SnapStay Studios",
      image: "https://i.pravatar.cc/150?u=snapstay",
      isVerified: true,
    },
    description: "Professional HDR photography for your listing. Includes 20+ edited photos, virtual tour, and floor plan. Boost your bookings.",
    duration: "2 hours",
    isPopular: true,
    highlights: ["HDR photography", "Virtual tour included", "24h delivery"],
  },
  {
    id: "svc-3",
    title: "Private Chef — Pakistani Cuisine",
    category: "chef",
    image: "https://images.unsplash.com/photo-1577219491135-ce391730fb2c?w=600&q=80",
    location: "Lahore, Pakistan",
    rating: 4.96,
    reviews: 184,
    price: 60,
    priceUnit: "per person",
    provider: {
      name: "Chef Amina",
      image: "https://i.pravatar.cc/150?u=chefamina",
      isVerified: true,
    },
    description: "An unforgettable dining experience in your accommodation. Chef Amina prepares a 5-course traditional Pakistani feast with fresh local ingredients.",
    duration: "3 hours",
    isPopular: true,
    highlights: ["5-course meal", "Fresh ingredients", "Cleanup included"],
  },
  {
    id: "svc-4",
    title: "Airport Pickup & Transfer",
    category: "transport",
    image: "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=600&q=80",
    location: "Islamabad, Pakistan",
    rating: 4.90,
    reviews: 567,
    price: 25,
    priceUnit: "per trip",
    provider: {
      name: "RideEase Pakistan",
      image: "https://i.pravatar.cc/150?u=rideease",
      isVerified: true,
    },
    description: "Comfortable airport pickup with meet & greet. Clean vehicles, professional drivers, and flight tracking for on-time service.",
    duration: "Varies",
    isPopular: true,
    highlights: ["Flight tracking", "Meet & greet", "24/7 available"],
  },
  {
    id: "svc-5",
    title: "Personal Concierge Service",
    category: "concierge",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80",
    location: "Dubai, UAE",
    rating: 4.97,
    reviews: 321,
    price: 50,
    priceUnit: "per day",
    provider: {
      name: "LuxeStay Concierge",
      image: "https://i.pravatar.cc/150?u=luxestay",
      isVerified: true,
    },
    description: "Your personal assistant for everything — restaurant reservations, event tickets, tour bookings, and local recommendations.",
    duration: "Full day",
    isPopular: true,
    highlights: ["24/7 WhatsApp support", "Local expert", "Custom itineraries"],
  },
  {
    id: "svc-6",
    title: "In-Home Spa & Massage",
    category: "beauty",
    image: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=600&q=80",
    location: "Karachi, Pakistan",
    rating: 4.93,
    reviews: 156,
    price: 45,
    priceUnit: "per session",
    provider: {
      name: "Serenity Spa",
      image: "https://i.pravatar.cc/150?u=serenity",
      isVerified: true,
    },
    description: "Relax with a professional massage in the comfort of your accommodation. Choose from Swedish, deep tissue, or aromatherapy.",
    duration: "1-2 hours",
    isPopular: false,
    highlights: ["Licensed therapists", "Bring all supplies", "Multiple styles"],
  },
  {
    id: "svc-7",
    title: "Personal Fitness Trainer",
    category: "fitness",
    image: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600&q=80",
    location: "Islamabad, Pakistan",
    rating: 4.88,
    reviews: 89,
    price: 30,
    priceUnit: "per session",
    provider: {
      name: "FitPak Training",
      image: "https://i.pravatar.cc/150?u=fitpak",
      isVerified: true,
    },
    description: "Stay active during your trip. Certified trainer comes to your accommodation or a nearby park for a personalized workout session.",
    duration: "1 hour",
    isPopular: false,
    highlights: ["Certified trainer", "Custom workout plan", "Equipment provided"],
  },
  {
    id: "svc-8",
    title: "Trusted Babysitting Service",
    category: "childcare",
    image: "https://images.unsplash.com/photo-1587616211892-f743fcca64f9?w=600&q=80",
    location: "Lahore, Pakistan",
    rating: 4.94,
    reviews: 203,
    price: 20,
    priceUnit: "per hour",
    provider: {
      name: "KidsCare LHR",
      image: "https://i.pravatar.cc/150?u=kidscare",
      isVerified: true,
    },
    description: "Background-checked, CPR-certified babysitters available for your stay. Perfect for parents who want a night out.",
    duration: "Flexible",
    isPopular: false,
    highlights: ["Background checked", "CPR certified", "All ages"],
  },
  {
    id: "svc-9",
    title: "Pet Sitting & Dog Walking",
    category: "pet",
    image: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    location: "Islamabad, Pakistan",
    rating: 4.91,
    reviews: 67,
    price: 15,
    priceUnit: "per visit",
    provider: {
      name: "PawPals ISB",
      image: "https://i.pravatar.cc/150?u=pawpals",
      isVerified: true,
    },
    description: "Loving care for your furry friends. Daily walks, feeding, and playtime by experienced pet sitters who treat your pets like family.",
    duration: "1 hour per visit",
    isPopular: false,
    highlights: ["Experienced with all breeds", "Photo updates", "Insured"],
  },
  {
    id: "svc-10",
    title: "Deep Clean & Turnover Service",
    category: "cleaning",
    image: "https://images.unsplash.com/photo-1628177142898-93e36e4e3a50?w=600&q=80",
    location: "Karachi, Pakistan",
    rating: 4.92,
    reviews: 145,
    price: 55,
    priceUnit: "per turnover",
    provider: {
      name: "SparkleClean KHI",
      image: "https://i.pravatar.cc/150?u=sparkle",
      isVerified: true,
    },
    description: "Between-guest deep cleaning for Airbnb hosts. Linen change, restocking supplies, and a spotless property ready for the next guest.",
    duration: "4-5 hours",
    isPopular: true,
    highlights: ["Host-focused", "Linen service", "Restocking available"],
  },
  {
    id: "svc-11",
    title: "Private Chef — BBQ Specialist",
    category: "chef",
    image: "https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=600&q=80",
    location: "Islamabad, Pakistan",
    rating: 4.89,
    reviews: 98,
    price: 50,
    priceUnit: "per person",
    provider: {
      name: "Chef Kamran",
      image: "https://i.pravatar.cc/150?u=chefkamran",
      isVerified: true,
    },
    description: "Host the ultimate BBQ night. Chef Kamran brings premium meats, marinades, and grilling equipment for an outdoor feast to remember.",
    duration: "4 hours",
    isPopular: false,
    highlights: ["Premium meats", "All equipment provided", "Serves up to 20"],
  },
  {
    id: "svc-12",
    title: "Luxury Car Rental with Driver",
    category: "transport",
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=600&q=80",
    location: "Dubai, UAE",
    rating: 4.95,
    reviews: 278,
    price: 120,
    priceUnit: "per day",
    provider: {
      name: "LuxeDrive Dubai",
      image: "https://i.pravatar.cc/150?u=luxedrive",
      isVerified: true,
    },
    description: "Explore Dubai in style with a luxury vehicle and professional chauffeur. Fleet includes Mercedes, BMW, and Range Rover.",
    duration: "Full day",
    isPopular: true,
    highlights: ["Luxury fleet", "Professional chauffeur", "Fuel included"],
  },
  {
    id: "svc-13",
    title: "Event & Party Photography",
    category: "photography",
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&q=80",
    location: "Lahore, Pakistan",
    rating: 4.87,
    reviews: 134,
    price: 100,
    priceUnit: "per event",
    provider: {
      name: "FrameIt Studios",
      image: "https://i.pravatar.cc/150?u=frameit",
      isVerified: true,
    },
    description: "Capture your special moments with a professional event photographer. Weddings, birthdays, corporate events, and more.",
    duration: "4+ hours",
    isPopular: false,
    highlights: ["50+ edited photos", "Same-day preview", "Drone shots available"],
  },
  {
    id: "svc-14",
    title: "Hair & Makeup — Bridal Package",
    category: "beauty",
    image: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600&q=80",
    location: "Lahore, Pakistan",
    rating: 4.96,
    reviews: 189,
    price: 80,
    priceUnit: "per session",
    provider: {
      name: "GlowUp by Mehreen",
      image: "https://i.pravatar.cc/150?u=glowup",
      isVerified: true,
    },
    description: "Professional bridal hair and makeup at your venue. Includes trial session, day-of styling, and touch-up kit.",
    duration: "3 hours",
    isPopular: true,
    highlights: ["Trial included", "Premium products", "Touch-up kit"],
  },
  {
    id: "svc-15",
    title: "Guided City Tour with Driver",
    category: "concierge",
    image: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=600&q=80",
    location: "Karachi, Pakistan",
    rating: 4.84,
    reviews: 112,
    price: 35,
    priceUnit: "per person",
    provider: {
      name: "CityExplore KHI",
      image: "https://i.pravatar.cc/150?u=cityexplore",
      isVerified: false,
    },
    description: "Full-day guided tour of Karachi's top attractions — Clifton Beach, Mohatta Museum, Port Grand, and more. AC transport included.",
    duration: "8 hours",
    isPopular: false,
    highlights: ["AC transport", "Local guide", "Lunch stop included"],
  },
  {
    id: "svc-16",
    title: "Outdoor Yoga Session",
    category: "fitness",
    image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600&q=80",
    location: "Islamabad, Pakistan",
    rating: 4.93,
    reviews: 76,
    price: 18,
    priceUnit: "per session",
    provider: {
      name: "ZenFit ISB",
      image: "https://i.pravatar.cc/150?u=zenfit",
      isVerified: true,
    },
    description: "Start your morning with an outdoor yoga session in Fatima Jinnah Park. All levels welcome, mats and water provided.",
    duration: "1.5 hours",
    isPopular: false,
    highlights: ["All levels", "Mats provided", "Scenic location"],
  },
];

export default services;

/* ─── Helper: get service by ID ─── */
export const getServiceById = (id) =>
  services.find((s) => s.id === id) || null;
